#!/usr/bin/expect

#Prompt->ell"
#File="test.txt"
spawn ./a.out
expect "Prompt->"
#while read p; 
#do
#done <test.txt
send "cd\n"
expect "Prompt->"
send "cd\n"
expect "Prompt->"
send "cd ..\n"
expect "Prompt->"
send "cd .\n"
expect "Prompt->"
send "cd /Usersn\n"
expect "Prompt->"
send "cd //\n"
expect "Prompt->"
send "cd '//'\n"
expect "Prompt->"
send "cd //////\n"
expect "Prompt->"
send "cd ./././\n"
expect "Prompt->"
send "cd /\n"
expect "Prompt->"
send "cd '/etc'\n"
expect "Prompt->"
send "cd '/var'\n"
expect "Prompt->"
send "cd \"\$PWD/prompt\"\n"
expect "Prompt->"
send "cd \"doesntexist\"\n"
expect "Prompt->"
send "cd \"doesntexist\"\n"
expect "Prompt->"
send "cd ../../..\n"
expect "Prompt->"
send "cd ..\n"
expect "Prompt->"
send "cd ..\n"
expect "Prompt->"
send "cd ?\n"
expect "Prompt->"
send "cd +\n"
expect "Prompt->"
send "cd _\n"
expect "Prompt->"
send "cd bark\n"
expect "Prompt->"
send "cd '/'\n"
expect "Prompt->"
send "cd \$PWD/file_tests\n"
expect "Prompt->"
send "cd \$OLDPWD/builtins\n"
expect "Prompt->"
send "echo\n"
expect "Prompt->"
send "echo echo\n"
expect "Prompt->"
send "eCho\n"
expect "Prompt->"
send "eChO\n"
expect "Prompt->"
send "eCHO\n"
expect "Prompt->"
send "echo $\n"
expect "Prompt->"
send "echo $\n"
expect "Prompt->"
send "ECHO\n"
expect "Prompt->"
send "echo rhobebou\n"
expect "Prompt->"
send "echo stop\n"
expect "Prompt->"
send "echo \"bonjour\"\n"
expect "Prompt->"
send "echo bonjour\n"
expect "Prompt->"
send "echo 'bonjour'\n"
expect "Prompt->"
send "echo -n\n"
expect "Prompt->"
send "echo -nn\n"
expect "Prompt->"
send "echo -n\n"
expect "Prompt->"
send "echo \"-n\"\n"
expect "Prompt->"
send "echo -n\"-n\"\n"
expect "Prompt->"
send "echo \"-nnnn\"\n"
expect "Prompt->"
send "echo \"-nnnn\"\n"
expect "Prompt->"
send "echo \"-n\n"
expect "Prompt->"
send "echo \"-n\n"
expect "Prompt->"
send "echo \$USER\n"
expect "Prompt->"
send "echo \"\$USER\"\n"
expect "Prompt->"
send "echo \"\'\$USER\'\"\n"
expect "Prompt->"
send "echo \"\n"
expect "Prompt->"
send "echo text\"\$USER\"\n"
expect "Prompt->"
send "echo text\"\'\$USER'\"\n"
expect "Prompt->"
send "echo \"text\"\n"
expect "Prompt->"
send "echo '\n"
expect "Prompt->"
send "echo text\n"
expect "Prompt->"
send "echo \'\'\'\'\'\'\'\'\'\'\$USER\'\'\'\'\'\'\'\'\'\'\n"
expect "Prompt->"
send "echo \"\"\"\"\"\"\"\"\$USER\"\"\"\"\"\"\"\"\n"
expect "Prompt->"
send "echo \$USER'\$USER'text\n"
expect "Prompt->"
send "echo \$USER\n"
expect "Prompt->"
send "echo \'\n"
expect "Prompt->"
send "echo \'\"\n"
expect "Prompt->"
send "echo \\\"\n"
expect "Prompt->"
send "echo \"\$USER\"\"\$USER\"\"\$USER\"\n"
expect "Prompt->"
send "echo text\"\$USER\"test\n"
expect "Prompt->"
send "echo \'\$USER\'\n"
expect "Prompt->"
send "echo '\$USER'\n"
expect "Prompt->"
send "echo \$USER\n"
expect "Prompt->"
send "echo \"\$USER\"\"Users/\$USER/file\"\"'\$USER'\"'\$USER\n"
expect "Prompt->"
send "echo \"\$USER\$USER\$USER\"\n"
expect "Prompt->"
send "echo \'\$USER\'\"\$USER\"\'\$USER\'\n"
expect "Prompt->"
send "echo '\"\$USER\"\'\'\$USER\'\"\"\"\$USER\"\n"
expect "Prompt->"
send "echo \"\n"
expect "Prompt->"
send "echo \"\n"
expect "Prompt->"
send "echo \$USER=4\n"
expect "Prompt->"
send "echo \$USER=thallard\n"
expect "Prompt->"
send "echo \$USER\n"
expect "Prompt->"
send "echo \$?\n"
expect "Prompt->"
send "echo \$PWD/file\n"
expect "Prompt->"
send "echo \"\$PWD/fil\"\n"
expect "Prompt->"
send "echo \"text\"\n"
expect "Prompt->"
send "echo \$PWD\n"
expect "Prompt->"